### ISSUE TITLE
App not working without Alarms and Reminders permission

### ISSUE THREAD

**Issue by adamkona** [AlfaazPlus/QuranApp#100]
### Steps to reproduce

Turn off the alarms and reminders permission and the app doesn't open.

### Expected behavior

The app opens as normal

### Actual behavior

Crashes instantly

### QuranApp version

2023.03.05.1

### Android version

13

### Other details

I have also found that with this permission enabled that an alarm is shown on my lockscreen at 4am even though this alarm never goes off.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Thank you for reporting. I have not tested this app for Android 13 fully. The alarm permission is still in the todo. It's strange that it doesn't open when you don't give the alarm permission. I will have to fix it. Moreover, can you post a screen video here showing the actual issue?

**Comment by faisalcodes** [comment]
Currently, I am focused on #87 and #88. If you can't copy the stack trace because the app doesn't even open, if possible kindly build the debug variant of this project on your machine and copy the stack trace from Android studio's `Device file manager`. The crash log is saved under the shared preference folder with filename `sp_crash_log.xml`.

**Comment by adamkona** [comment]
```
type: crash
osVersion: google/bluejay/bluejay:13/TQ1A.230205.002/2023030400:user/release-keys
package: com.quranapp.android:230305001
process: com.quranapp.android
processUptime: 141 + 197 ms

java.lang.SecurityException: Caller com.quranapp.android needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:310)
	at android.app.AlarmManager.setImpl(AlarmManager.java:980)
	at android.app.AlarmManager.setImpl(AlarmManager.java:932)
	at android.app.AlarmManager.setAlarmClock(AlarmManager.java:833)
	at s6.a.a(VOTDUtils.java:101)
	at com.quranapp.android.activities.MainActivity.G(MainActivity.java:328)
	at f.w.run(R8$$SyntheticClass:142)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.alarm.AlarmManagerService$5.set(AlarmManagerService.java:2922)
	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:182)
	at android.os.Binder.execTransactInternal(Binder.java:1302)
	at android.os.Binder.execTransact(Binder.java:1265)


```

**Comment by adamkona** [comment]
I managed to get a stack trace

**Comment by adamkona** [comment]
![Screenshot_20230312-201458](https://user-images.githubusercontent.com/20659452/224571249-ce39d876-98aa-4709-8d85-f5e1b7473c62.png)
Based on this permission

**Comment by adamkona** [comment]
![IMG_20230312_202346](https://user-images.githubusercontent.com/20659452/224571451-f2c13d89-cd2e-4a00-92ae-ab7187113407.jpg)
The alarm here for 4am turns off when I turn alarm permissions off for the app

**Comment by faisalcodes** [comment]
I get it. This will be fixed in the next release inshallah.

> The alarm here for 4am turns off when I turn alarm permissions off for the app

Yes that's intended. QuranApp provides you a Verse of the Day feature which sets a 4am alarm to remind you of a verse daily. Don't worry! It does not play a loud ring rather it only sends you a notification. You may turn VOTD off in the settings.

I have also planned to implement custom reminder in which you will be able to set reminder of custom verse at custom time. It is in the roadmap.

**Comment by adamkona** [comment]
Jazakallah khair for your speed resolving this! I'm really enjoying using this app by the way! May Allah SWT reward you for your efforts :D

**Comment by faisalcodes** [comment]
Aameen ❤️

**Comment by faisalcodes** [comment]
The changes will be reflected in the next release. Meanwhile you can keep using the app by allowing the permissions or install the [debug apk](https://github.com/AlfaazPlus/QuranApp/actions/runs/4403058277) for the changes.
