### ISSUE TITLE
App crash with bookmarks

### ISSUE THREAD

**Issue by GoRaN909** [AlfaazPlus/QuranApp#111]
### Steps to reproduce

Bookmark some ayat then try to see it or edit notes the app crashes suddenly, This happens with debug app i tested to see my language Kurdish that have any mistakes or typo also when app lang is set to کوردی the audio(reciter) files cannot be played.

### Expected behavior

..

### Actual behavior

..

### QuranApp version

2023.03.05.2-debug

### Android version

Android 13 - OneUI 5.1

### Other details

java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at android.text.SpannableString.<init>(SpannableString.java:34)
	at android.text.SpannableString.<init>(SpannableString.java:43)
	at com.quranapp.android.adapters.ADPBookmark.prepareTexts(ADPBookmark.java:135)
	at com.quranapp.android.adapters.ADPBookmark.access$200(ADPBookmark.java:38)
	at com.quranapp.android.adapters.ADPBookmark$VHBookmark.bind(ADPBookmark.java:167)
	at com.quranapp.android.adapters.ADPBookmark.onBindViewHolder(ADPBookmark.java:122)
	at com.quranapp.android.adapters.ADPBookmark.onBindViewHolder(ADPBookmark.java:38)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1427)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4917)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4240)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:852)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
The problem is here. The datetime object is null.

https://github.com/AlfaazPlus/QuranApp/blob/3c9b91af557dd2e294d631ee575a65c2938fa520/app/src/main/java/com/quranapp/android/adapters/ADPBookmark.java#L135

**Comment by faisalcodes** [comment]
The datetime was not saved somehow. Open `device file explorer` in the android studio and delete the `Bookmark.db` located at `data/data/com.quranapp.android.debug/databases/` and then try to bookmark again.

**Comment by GoRaN909** [comment]
> The datetime was not saved somehow. Open `device file explorer` in the android studio and delete the `Bookmark.db` located at `data/data/com.quranapp.android.debug/databases/` and then try to bookmark again.

Thanks for explaining bro but there is no that folder name `data/data/com.quranapp.android.debug` the folder is not available I tried on phone and also from android studio file explorer that's so strange.
