### ISSUE TITLE
Unable to fetch Reciter. 

### ISSUE THREAD

**Issue by fard33n** [AlfaazPlus/QuranApp#184]
### Steps to reproduce

1.Open QuranApp.

2. Go to settings.

3. Select Reciter.

4. And then the issue occurs. 

### Expected behavior

When you click on the reciter it should expand to a list of reciters. 

### Actual behavior

Clicking on the select reciter shows the loading bar for a while then shows no recitations available. 

### QuranApp version

2023.04.02.1

### Android version

Android 13

### Other details

Shows the same behaviour for Tafseer as well. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by ciaociaoweb** [comment]
Here is an attachment. 
![IMG_20230404_151225_325](https://user-images.githubusercontent.com/105258592/229753792-b29c970e-64b2-40db-ac2b-3b90d6f75270.jpg)

**Comment by ARBoyGo** [comment]
When I opened, It is not fetch at first but clicking reload button does the job.

**Comment by ciaociaoweb** [comment]
Not for me.
Device Redmi 4A
OS: LineageOS 20 based on Android 13.
https://user-images.githubusercontent.com/105258592/229760085-7eb352a4-0243-4d23-b09f-1e9e18691d71.mp4

**Comment by faisalcodes** [comment]
@ciaociaoweb Can you retrieve the logcat of the app from the device?

**Comment by ciaociaoweb** [comment]
I was about to. This showed up when I reopened the app after the above screen recording.


java.lang.NullPointerException: Parameter specified as non-null is null: method o5.d.a, parameter slug
 at o5.d.a(RecitationManager.kt:3)
 at u4.k.l(R8$$SyntheticClass:121)
 at o5.d$a.i(RecitationManager.kt:7)
 at o5.c$b.o(RecitationManager.kt:7)
 at f7.a.m(ContinuationImpl.kt:9)
 at v7.f0.run(DispatchedTask.kt:107)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7884)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
 Suppressed: v7.d0: [f1{Cancelling}@3d5f54b, Dispatchers.IO]

**Comment by ciaociaoweb** [comment]
> @ciaociaoweb Can you retrieve the logcat of the app from the device?

I was about to. This showed up when I reopened the app after the above screen recording.


**java.lang.NullPointerException: Parameter specified as non-null is null: method o5.d.a, parameter slug
 at o5.d.a(RecitationManager.kt:3)
 at u4.k.l(R8$$SyntheticClass:121)
 at o5.d$a.i(RecitationManager.kt:7)
 at o5.c$b.o(RecitationManager.kt:7)
 at f7.a.m(ContinuationImpl.kt:9)
 at v7.f0.run(DispatchedTask.kt:107)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7884)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
 Suppressed: v7.d0: [f1{Cancelling}@3d5f54b, Dispatchers.IO]**

**Comment by faisalcodes** [comment]
Can you install the [debug apk](https://github.com/AlfaazPlus/QuranApp/actions/runs/4590004772) so that we can get more information?

**Comment by ciaociaoweb** [comment]
> Can you install the [debug apk](https://github.com/AlfaazPlus/QuranApp/actions/runs/4590004772) so that we can get more information?

I don't see an apk. How did I install it?

**Comment by faisalcodes** [comment]
Use [this link](https://github.com/AlfaazPlus/QuranApp/suites/11975033927/artifacts/628354533) you can't find the apk.

**Comment by ciaociaoweb** [comment]
> Use [this link](https://github.com/AlfaazPlus/QuranApp/suites/11975033927/artifacts/628354533) you can't find the apk.

Got it. What am I supposed to do with it?

**Comment by faisalcodes** [comment]
Kindly install the apk on the custom ROM and get the logcat if possible. If that doesn't work then clone this repository to your local machine, build and run to get logcat from the Android Studio.

**Comment by ciaociaoweb** [comment]
> Kindly install the apk on the custom ROM and get the logcat if possible. If that doesn't work then clone this repository to your local machine, build and run to get logcat from the Android Studio.

Well....


https://user-images.githubusercontent.com/105258592/229787801-a5e3bd35-04f7-4021-87e8-8ef9af8429a8.mp4

**Comment by faisalcodes** [comment]
Kindly join our [discord](https://discord.gg/wWuR3HHx) for detailed communication.

**Comment by ciaociaoweb** [comment]
> Kindly join our [discord](https://discord.gg/wWuR3HHx) for detailed communication.

Joined.
