### ISSUE TITLE
App crashes when language set to arabic

### ISSUE THREAD

**Issue by Zakaria-ouertani** [AlfaazPlus/QuranApp#193]
When i set language to english it works fine

I had to quickly copy this error before it crashes

```java
java.util.IllegalFormatConversionException: d != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4402)
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2884)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2838)
	at java.util.Formatter.format(Formatter.java:2529)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2814)
	at android.content.res.Resources.getString(Resources.java:530)
	at android.content.Context.getString(Context.java:576)
	at l5.c.a(ParserUtils.kt:62)
	at l5.f.a(QuranDuaParser.kt:83)
	at l5.e.run(R8$$SyntheticClass:51)
	at java.lang.Thread.run(Thread.java:784)
```

**Comment by faisalcodes** [comment]
The Arabic language translation is not yet completed. The crash is due to a misplaced string format identifier. I have fixed it, kindly wait for the next release.
