### ISSUE TITLE
App crashes when choose Arabic language 

### ISSUE THREAD

**Issue by amrelhossieny** [AlfaazPlus/QuranApp#197]
### Steps to reproduce

When change language to arabic it crashes here is the crash log 

Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: POCO F1
[Display]: TKQ1.220829.002 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: en_US
[Process ID]: 25927
[CPU ABI]: none
[Package Name]: com.quranapp.android
[Version Name]: 2023.04.02.1
[Version Code]: 230402001
[Error Type]: JVM
[Crash Time]: 2023-04-07T05:09:40.999
[Stack Trace]:
java.util.IllegalFormatConversionException: d != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4408)
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2890)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2844)
	at java.util.Formatter.format(Formatter.java:2535)
	at java.util.Formatter.format(Formatter.java:2464)
	at java.lang.String.format(String.java:3644)
	at android.content.res.Resources.getString(Resources.java:590)
	at android.content.Context.getString(Context.java:788)
	at l5.c.a(ParserUtils.kt:62)
	at l5.f.a(QuranDuaParser.kt:83)
	at l5.e.run(R8$$SyntheticClass:51)
	at java.lang.Thread.run(Thread.java:1012)

### Expected behavior

The app force closes 

### Actual behavior

.

### QuranApp version

2023.04.02.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Fixed in #194.
