### ISSUE TITLE
App crash when no internet connections! 

### ISSUE THREAD

**Issue by GoRaN909** [AlfaazPlus/QuranApp#233]
### Steps to reproduce

1- Turn off internet wifi/mobile data
2- Open QuranApp (debug) with new audio player
3- Goto manage audio tap on any reciter

App crashes suddenly.

### Expected behavior

I think the crash is because the host-url or something like that maybe...

### Actual behavior

It should show no interet connection available like the translation downloader screen.

### QuranApp version

2023.04.02.1-debug

### Android version

Android 13 - OneUI 5.1

### Other details

Here is crash log:

```
java.net.UnknownHostException: Unable to resolve host "verses.quran.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at java.net.URL.openStream(URL.java:1072)
	at com.quranapp.android.utils.services.RecitationChapterDownloadService$download$2.invokeSuspend(RecitationChapterDownloadService.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: java.net.UnknownHostException: Unable to resolve host "verses.quran.com": No address associated with hostname
		at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
		... 26 more
	Suppressed: java.net.UnknownHostException: Unable to resolve host "verses.quran.com": No address associated with hostname
		at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
		... 26 more
	Suppressed: java.net.UnknownHostException: Unable to resolve host "verses.quran.com": No address associated with hostname
		... 27 more
	Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
		at libcore.io.Linux.android_getaddrinfo(Native Method)
		at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
		at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
		at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
		at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
		... 26 more
	Suppressed: java.net.UnknownHostException: Unable to resolve host "verses.quran.com": No address associated with hostname
		at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
		... 26 more
	Suppressed: java.net.UnknownHostException: Unable to resolve host "verses.quran.com": No address associated with hostname
		at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
		... 26 more
	Suppressed: java.net.UnknownHostException: Unable to resolve host "verses.quran.com": No address associated with hostname
		... 27 more
	Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
		at libcore.io.Linux.android_getaddrinfo(Native Method)
		at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
		at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
		at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
		at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
		... 26 more
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1c425eb, Dispatchers.Main]
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 26 more

```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
I have already told you for you branch, it won't work without a host-url. The crash happens only for your branch.

**Comment by faisalcodes** [comment]
Let me see then.
