### ISSUE TITLE
Cannot load recitations 

### ISSUE THREAD

**Issue by wutisdis** [AlfaazPlus/QuranApp#327]
### Steps to reproduce

1. Refresht the list of recitations in the recitations menu
2. Repeat because it does not work :/

### Expected behavior

Shouldbload recitations

### Actual behavior

Fails to load:
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at sa.v.b(SourceFile:2516)
	at sa.z0.e(SourceFile:31)
	at sa.y0.invoke(SourceFile:45)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy2.d(Unknown Source)
	at g7.f.j(SourceFile:50)
	at y8.a.i(SourceFile:9)
	at n9.d0.run(SourceFile:111)
	at kotlinx.coroutines.internal.d.run(SourceFile:12)
	at kotlinx.coroutines.scheduling.i.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)

### QuranApp version

2023.05.22.1

### Android version

Android 13

### Other details

Does not work in either WIFI or mobile data
Tried play store and fdroid versions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
It has been fixed in version [2023.05.23.3](https://github.com/AlfaazPlus/QuranApp/pull/326)

Kindly update the app from the Play Store. If you have downloaded the apk from GitHub, wait until tonight I add the new apk in the latest release.
