### ISSUE TITLE
App Crashing when downloading translation

### ISSUE THREAD

**Issue by ghost** [AlfaazPlus/QuranApp#365]
### Steps to reproduce

java.lang.NoClassDefFoundError: Failed resolution of: [Ljava/nio/file/attribute/FileAttribute;
at l7.d0.j(SourceFile:34)
at y8.a.i(SourceFile:9)
at n9.d0.run(SourceFile:111)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Suppressed: n9.b0: [g1{Cancelling}@3cc2586, Dispatchers.Main]
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.attribute.FileAttribute" on path: DexPathList[[zip file "/data/app/com.quranapp.android-2/base.apk"],nativeLibraryDirectories=[/data/app/com.quranapp.android-2/lib/arm, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
... 10 more
Suppressed: java.lang.ClassNotFoundException: java.nio.file.attribute.FileAttribute
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 11 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

### Expected behavior

Crashing

### Actual behavior

Crashing

### QuranApp version

2023.07.02.1

### Android version

Android 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by Luciogi** [comment]
clear app data, then try

**Comment by Justauser0** [comment]
> clear app data, then try

Still not working

**Comment by faisalcodes** [comment]
Android 6 is a very old phone. There might be some compatibility issue. It is more likely due to proguard.

**Comment by Luciogi** [comment]
https://github.com/AlfaazPlus/QuranApp/releases/tag/2023.04.21.1
try this release

**Comment by Justauser0** [comment]
> https://github.com/AlfaazPlus/QuranApp/releases/tag/2023.04.21.1 try this release

Still not working

**Comment by Luciogi** [comment]
something is wrong with specifically your device

**Comment by Justauser0** [comment]
> something is wrong with specifically your device

Is there any solution

**Comment by GoRaN909** [comment]
> > something is wrong with specifically your device
> 
> Is there any solution

Yeah just Upgrade your phone to any nowadays phones that released with newer Android version like A11+

**Comment by Luciogi** [comment]
is your phone rooted ?

**Comment by faisalcodes** [comment]
Closing this as stale.
