### ISSUE TITLE
Crashes when downloading translations

### ISSUE THREAD

**Issue by metehanc8s9** [AlfaazPlus/QuranApp#416]
### Steps to reproduce

1. Go to download Quran translation menu
2. Choose a translation and try to download it
3. Confirm downloading
4. It crashes

### Expected behavior

It should download translation but not crash

### Actual behavior

It crashed

### QuranApp version

2023.09.17.1

### Android version

Android 7

### Other details

Crash log:

java.lang.NoClassDefFoundError: Failed resolution of: [Ljava/nio/file/attribute/FileAttribute;
	at m7.d0.i(SourceFile:34)
	at a9.a.j(SourceFile:9)
	at p9.d0.run(SourceFile:111)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
	Suppressed: p9.b0: [g1{Cancelling}@cda6991, Dispatchers.Main]
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.attribute.FileAttribute" on path: DexPathList[[zip file "/data/app/com.quranapp.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.quranapp.android-1/lib/arm64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 10 more

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by Luciogi** [comment]
similar to #365

**Comment by metehanc8s9** [comment]
> similar to #365

Yes but Android version is different so I wanted to ask
