### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by ahmad954** [AlfaazPlus/QuranApp#429]
### Steps to reproduce

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1574)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1602)
	at m7.r.i(SourceFile:334)
	at a9.a.j(SourceFile:9)
	at p9.d0.run(SourceFile:103)
	at android.os.Handler.handleCallback(Handler.java:94... 478 more chars

### Expected behavior

Open the app normally 

### Actual behavior

p9.d0.run

### QuranApp version

2023.09.17.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Please explain the issue properly next time. How and when does this happen.
