### ISSUE TITLE
App crashes sometimes when I open vlc side by side quran app

### ISSUE THREAD

**Issue by iamtalhaasghar** [AlfaazPlus/QuranApp#446]
java.lang.RuntimeException: Unable to pause activity {com.quranapp.android/com.quranapp.android.activities.ActivityReader}: java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.recyclerview.widget.LinearLayoutManager.L0()' on a null object reference
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5266)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5217)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6028)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5953)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.recyclerview.widget.LinearLayoutManager.L0()' on a null object reference
	at com.quranapp.android.activities.ActivityReader.f0(SourceFile:3)
	at com.quranapp.android.activities.ActivityReader.onPause(SourceFile:2)
	at android.app.Activity.performPause(Activity.java:8392)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5256)
	... 13 more

**Comment by iamtalhaasghar** [comment]
obviously i need to provide more details. Will do if it happens again!

**Comment by Luciogi** [comment]
it simply mean application does not support split screen

**Comment by iamtalhaasghar** [comment]
> it simply mean application does not support split screen

If i open vlc in picture-in-picture mode with Qruan App in full screen mode, the setup works fine. Its just when i minimize Quran app to open something else it crashes sometimes.
