### ISSUE TITLE
The app keeps crashing while opening "topics"

### ISSUE THREAD

**Issue by Mashrafidipto** [AlfaazPlus/QuranApp#80]
### Steps to reproduce

When opening "Topics in Quran"

### Expected behavior

The app should open the topics

### Actual behavior

the app crashes

### QuranApp version

2023.03.01.1

### Android version

Android 12

### Other details

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Typeface.getStyle()' on a null object reference
	at x3.d.a(TypefaceSpan2.java:15)
	at x3.d.updateMeasureState(TypefaceSpan2.java:1)
	at android.text.MeasuredParagraph.applyMetricsAffectingSpan(MeasuredParagraph.java:585)
	at android.text.MeasuredParagraph.buildForStaticLayout(MeasuredParagraph.java:427)
	at android.text.PrecomputedText.createMeasuredParagraphs(PrecomputedText.java:436)
	at android.text.StaticLayout.generate(StaticLayout.java:683)
	at android.text.StaticLayout.<init>(StaticLayout.java:591)
	at android.text.StaticLayout.<init>(StaticLayout.java:49)
	at android.text.StaticLayout$Builder.build(StaticLayout.java:416)
	at android.widget.TextView.makeSingleLayout(TextView.java:9305)
	at android.widget.TextView.makeNewLayout(TextView.java:9124)
	at android.widget.TextView.onMeasure(TextView.java:9508)
	at androidx.appcompat.widget.AppCompatTextView.onMeasure(AppCompatTextView.java:17)
	at android.view.View.measure(View.java:26196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26196)
	at androidx.recyclerview.widget.LinearLayoutManager.W0(LinearLayoutManager.java:150)
	at androidx.recyclerview.widget.LinearLayoutManager.J0(LinearLayoutManager.java:54)
	at androidx.recyclerview.widget.LinearLayoutManager.c0(LinearLayoutManager.java:920)
	at androidx.recyclerview.widget.RecyclerView.s(RecyclerView.java:35)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:62)
	at android.view.View.measure(View.java:26196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.r(CoordinatorLayout.java:7)
	at h2.e.i(HeaderScrollingViewBehavior.java:93)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:400)
	at android.view.View.measure(View.java:26196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:160)
	at android.view.View.measure(View.java:26196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:829)
	at android.view.View.measure(View.java:26196)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3783)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2557)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2836)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2272)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1160)
	at android.view.Choreographer.doCallbacks(Choreographer.java:950)
	at android.view.Choreographer.doFrame(Choreographer.java:879)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1142)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8309)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Thank you for reporting. It will be fixed shortly, Inshallah.
